Global:
  cal_metric_during_train: True
  character_dict_path: "/home/ai22/Documents/VUTT/ocr_reg_datasets/vi_dict_full.txt"
  character_type: vi
  checkpoints:
  debug: False
  distributed: True
  epoch_num: 20
  eval_batch_step: [ 0, 2000 ]
  infer_img: /home/ai22/Documents/ocr_reg_datasets/images1/7171.jpg
  infer_mode: False
  log_smooth_window: 20
  max_text_length: 60
  pretrained_model:  /home/ai22/Documents/VUTT/ocr_reg_datasets/en_PP-OCRv3_rec_train/best_accuracy
  print_batch_step: 100
  save_epoch_step: 10
  save_inference_dir:
  save_model_dir: ./output/v3_en_mobile
  save_res_path: ./output/rec/sar_ctc_dml.txt
  use_gpu: True
  use_space_char: True
  use_visualdl: True

Architecture:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          encoder_type: mobilevit
          Head:
            fc_decay: 0.00001
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
      - SARHead:
          enc_dim: 512
          max_text_length: 60
  Transform:
  algorithm: SAR
  model_type: rec

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: /home/ai22/Documents/VUTT/ocr_reg_datasets/ocr_reg_val_lmdb/
    transforms:
      - DecodeImage:
          channel_first: False
          img_mode: BGR
      - MultiLabelEncode:
      - SARRecResizeImg:
          image_shape: [ 3, 48, 48, 320 ]
          width_downsample_ratio: 0.25
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_sar
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 32
    drop_last: False
    num_workers: 4
    shuffle: False

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

Metric:
  name: RecMetric

Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
    name: Cosine
    warmup_epoch: 5
  name: Adam
  regularizer:
    factor: 1e-05
    name: L2

PostProcess:
  name: CTCLabelDecode

Train:
  dataset:
    name: LMDBDataSet
    data_dir: /home/ai22/Documents/VUTT/ocr_reg_datasets/ocr_reg_train_lmdb/
    transforms:
      - DecodeImage:
          channel_first: False
          img_mode: BGR
      - RecAug:
      - MultiLabelEncode:
      - SARRecResizeImg:
          image_shape: [ 3, 48, 48, 320 ]
          width_downsample_ratio: 0.25
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_sar
            - length
            - valid_ratio
  loader:
    batch_size_per_card: 32
    drop_last: True
    num_workers: 4
    shuffle: True